### ISSUE TITLE
showTotalItemsQty prop is not working

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/minicart#233]
**Describe the bug**
I found in the react files a prop that shoul display all the products in the card, not only the unique items. This prop is called "showTotalItemsQty" but if I set it to true, the minicart seems to ignore it. Any ideas what am I doing wrong?

https://github.com/vtex-apps/minicart/blob/master/react/index.jsx#L149

**To Reproduce**

1. Define the minicart blocks
2. Set the prop "showTotalItemsQty":true

**Expected behavior**
Should render a total number of products in cart

**Screenshots**

![image](https://user-images.githubusercontent.com/42587916/84671217-c7e1a900-af2f-11ea-8b8c-2b64cd9e5caf.png)

**Additional context**
Workspace beta on account sanovita
https://beta--sanovita.myvtex.com/

Thank you!

**Comment by victorhmp** [comment]
Hi @doruradu !

This prop is not part of the `minicart.v2` API. You can see the supported props in the docs: https://github.com/vtex-apps/minicart/blob/master/docs/README.md or https://vtex.io/docs/app/vtex.minicart .

To achieve what you're trying to do, you might use the `quantityDisplay`.

Closing this since it's not a bug :)
